spring.application.name: oauth2-client
server:
  port: 8081

spring:
  security:
    oauth2:
      client:
        registration:
          springoauth2:
            client-id: oauth2-client-app1
            client-secret: secret1
            scope: openid,read,write,photo,friend
            authorization-grant-type: authorization_code
            redirect-uri: http://127.0.0.1:8081/login/oauth2/code/springoauth2
        provider:
          springoauth2:
            issuer-uri: http://localhost:9000
