spring.application.name: spring-security-oauth2

server:
  port: 8081

spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            clientId: oauth2-client-app
            clientSecret: 1tIeERcVJnWNmVZIEFA7Ao5YkTIbx83w
            clientName: oauth2-client-app
            authorizationGrantType: authorization_code
            redirectUri: http://localhost:8081/login/oauth2/code/keycloak
            clientAuthenticationMethod: client_secret_basic
            scope: openid,profile
          keycloakWithPKCE:
            provider: keycloak
            clientId: oauth2-client-app2
            clientSecret: QSqs5YgObgPaCtSwbyUVNJYgCGU1tkcj
            clientName: oauth2-client-app2
            authorizationGrantType: authorization_code
            redirectUri: http://localhost:8081/login/oauth2/code/keycloak
            clientAuthenticationMethod: client_secret_basic
            scope: openid,profile
        provider:
          keycloak:
            issuerUri: http://localhost:8080/realms/oauth2
            authorizationUri: http://localhost:8080/realms/oauth2/protocol/openid-connect/auth
            tokenUri: http://localhost:8080/realms/oauth2/protocol/openid-connect/token
            jwkSetUri: http://localhost:8080/realms/oauth2/protocol/openid-connect/certs
            userInfoUri: http://localhost:8080/realms/oauth2/protocol/openid-connect/userinfo
            userNameAttribute: preferred_username
