spring.application.name: oauth2-resource-server
server:
  port: 8082
spring:
  security:
    oauth2:
      resourceserver:
        opaquetoken:
          introspection-uri: http://localhost:9000/oauth2/introspect
          client-id: oauth2-client-app1
          client-secret: secret1
